### ISSUE TITLE
Error: Cannot publish on branch master

### ISSUE THREAD

**Issue by mikelor** [jekyller/jasper2#122]
First of all thanks for this template and what looks like keeping an active community going.

I'm new to Jekyll, so this could be a newbie error. I have since resolved it, but want to make sure I did it the "right" way, and perhaps provide an update to help others if it is correct.

I'm using GitHub Actions to post my changes. Whenever I committed code however, the build would fail on the helaili/jeckyll-action build step with
`“Error: Cannot publish on branch master”`

To fix this I modified the [jekyll_build.yml](https://github.com/jekyller/jasper2/blob/master/.github/workflows/jekyll_build.yml)
 ```
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
```

Adding the `target_branch: 'gh-pages'` fixed the error.
